title:            Marcelo Pinheiro
email:            salizzar&#64;gmail.com
description: >
  Habemvs Epiphania: Random thoughts about programming, system administration,
  DevOps culture and personal weirdness.

baseurl:          "" # the subpath of your site, e.g. /blog/
url:              http://salizzar.net
twitter_username: salizzar
github_username:  salizzar

markdown:         kramdown
